CONSUMER_KEY = "*****"
CONSUMER_SECRET = "********"
ACCESS_KEY = "*********"
ACCESS_SECRET = "*********"
Github_username = "fakhrirofi"
Github_password = "*******"
Github_repo = "fakhrirofi/database" #use another repo instead of primary repo
First_Keyword = "fess!" #primary keyword for tweet, vide, and image
Second_Keyword = "[quote]" #for make image quoted
Sub2_Keyword = "-s" #give image quoted name
Third_keyword = "[ask]" #ask admin
Admin_id = "********" 
