CONSUMER_KEY = "VALUE"
CONSUMER_SECRET = "VALUE"
ACCESS_KEY = "VALUE"
ACCESS_SECRET = "VALUE"
Github_username = "VALUE"
Github_password = "VALUE"
Github_repo = "VALUE" #use another repo instead of primary repo 
First_Keyword = "VALUE" #primary keyword for tweet, video, gif, and image
Second_Keyword = "VALUE" #make quoted image
Sub2_Keyword = "VALUE" #give quoted image name
Third_keyword = "VALUE" #ask admin, with send dm to admin account
Admin_id = "VALUE" #send dm to admin #search on google how to get twitter user id
